### ISSUE TITLE
Getting 0 success rate for kitchen environments

### ISSUE THREAD

**Issue by lakshitadodeja** [irom-princeton/dppo#34]
Hi, 

I have been trying to evaluate the performance of pretrained policies which works fine with other environments but I am getting 0 success rate with kitchen environment. I also created a new conda environment and only installed kitchen specific dependencies with `pip install -e .[kitchen]`  but the success rate was still 0. Here is my current config file (Also tried with mixed and partial) - 

```
defaults:
  - _self_
hydra:
  run:  
    dir: ${logdir}
_target_: agent.eval.eval_diffusion_agent.EvalDiffusionAgent

name: ${env_name}_eval_diffusion_mlp_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/gym-eval/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: ${oc.env:DPPO_LOG_DIR}/gym-pretrain/kitchen-complete-v0_pre_diffusion_mlp_ta4_td20/2024-10-20_16-47-42_42/checkpoint/state_8000.pt
normalization_path: ${oc.env:DPPO_DATA_DIR}/gym/${env_name}/normalization.npz

seed: 42
device: cuda:0
env_name: kitchen-complete-v0
obs_dim: 60
action_dim: 9
denoising_steps: 20
cond_steps: 1
horizon_steps: 4
act_steps: 4

n_steps: 70
render_num: 0

env:
  n_envs: 40
  name: ${env_name}
  max_episode_steps: 280
  reset_at_iteration: False
  save_video: False
  best_reward_threshold_for_success: 4
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: ${normalization_path}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

model:
  _target_: model.diffusion.diffusion.DiffusionModel
  predict_epsilon: True
  denoised_clip_value: 1.0
  #
  network_path: ${base_policy_path}
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    time_dim: 16
    mlp_dims: [256, 256, 256]
    cond_mlp_dims: [128, 32]
    residual_style: True
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  device: ${device}
```
